spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/litemall
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

pagehelper:
  offset-as-page-num: true
  page-size-zero: true