package com.hyy.db.domain;

import java.util.Date;

public class LitemallCouponUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.user_id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.coupon_id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Integer coupon_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.status
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.used_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Date used_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.start_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Date start_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.end_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Date end_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.order_id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.add_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Date add_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.update_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_coupon_user.deleted
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.id
     *
     * @return the value of litemall_coupon_user.id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.id
     *
     * @param id the value for litemall_coupon_user.id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.user_id
     *
     * @return the value of litemall_coupon_user.user_id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.user_id
     *
     * @param user_id the value for litemall_coupon_user.user_id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.coupon_id
     *
     * @return the value of litemall_coupon_user.coupon_id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Integer getCoupon_id() {
        return coupon_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.coupon_id
     *
     * @param coupon_id the value for litemall_coupon_user.coupon_id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setCoupon_id(Integer coupon_id) {
        this.coupon_id = coupon_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.status
     *
     * @return the value of litemall_coupon_user.status
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.status
     *
     * @param status the value for litemall_coupon_user.status
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.used_time
     *
     * @return the value of litemall_coupon_user.used_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Date getUsed_time() {
        return used_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.used_time
     *
     * @param used_time the value for litemall_coupon_user.used_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setUsed_time(Date used_time) {
        this.used_time = used_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.start_time
     *
     * @return the value of litemall_coupon_user.start_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.start_time
     *
     * @param start_time the value for litemall_coupon_user.start_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.end_time
     *
     * @return the value of litemall_coupon_user.end_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.end_time
     *
     * @param end_time the value for litemall_coupon_user.end_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.order_id
     *
     * @return the value of litemall_coupon_user.order_id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.order_id
     *
     * @param order_id the value for litemall_coupon_user.order_id
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.add_time
     *
     * @return the value of litemall_coupon_user.add_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Date getAdd_time() {
        return add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.add_time
     *
     * @param add_time the value for litemall_coupon_user.add_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setAdd_time(Date add_time) {
        this.add_time = add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.update_time
     *
     * @return the value of litemall_coupon_user.update_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.update_time
     *
     * @param update_time the value for litemall_coupon_user.update_time
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_coupon_user.deleted
     *
     * @return the value of litemall_coupon_user.deleted
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_coupon_user.deleted
     *
     * @param deleted the value for litemall_coupon_user.deleted
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}