package com.hyy.db.mapper;

import com.hyy.db.domain.LitemallCouponUser;
import com.hyy.db.domain.LitemallCouponUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LitemallCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    int countByExample(LitemallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    int deleteByExample(LitemallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    int insert(LitemallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    int insertSelective(LitemallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    List<LitemallCouponUser> selectByExample(LitemallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    LitemallCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    int updateByExampleSelective(@Param("record") LitemallCouponUser record, @Param("example") LitemallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    int updateByExample(@Param("record") LitemallCouponUser record, @Param("example") LitemallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    int updateByPrimaryKeySelective(LitemallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_coupon_user
     *
     * @mbggenerated Fri Feb 25 14:36:15 CST 2022
     */
    int updateByPrimaryKey(LitemallCouponUser record);
}